sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull mysql:latest
  - docker run --name users-mysql -e MYSQL_ROOT_PASSWORD=letmein -d -p 3306:3306 mysql:latest
  - docker exec users-mysql mysqladmin -uroot -pletmein create users