CREATE TABLE USERS (
    ID NVARCHAR(64) PRIMARY KEY,
    USERNAME NVARCHAR(255),
    PASSWORD NVARCHAR(255),
    STATUS NVARCHAR(64),
    UPDATED_DATE DATETIME,
    CREATED_DATE DATETIME NOT NULL DEFAULT (GETDATE()) 
);

CREATE TABLE USER_EVENT (
     ID BIGINT IDENTITY(1,1) NOT NULL,
     TAG_URI NVARCHAR(100) NOT NULL,
     USERS_ID BIGINT NOT NULL,
     UPDATED_DATE DATETIME,
     CREATED_DATE DATETIME NOT NULL DEFAULT (GETDATE())
);

-- TODO add primary keys, constraints and indexes 