CREATE TABLE USERS (
    ID            NVARCHAR(64) PRIMARY KEY,
    USERNAME      NVARCHAR(255),
    PASSWORD      NVARCHAR(255),
    STATUS        NVARCHAR(64),
    UPDATED_DATE  DATETIME,
    CREATED_DATE  DATETIME
);

CREATE TABLE USER_EVENT (
    ID            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TAG_URI       NVARCHAR(100) NOT NULL,
    USERS_ID      NVARCHAR(64) NOT NULL,
    UPDATED_DATE  DATETIME,
    CREATED_DATE  DATETIME
);

-- TODO add primary keys, constraints and indexes 